# Generated by Django 5.2.3 on 2025-06-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capital', models.IntegerField()),
                ('porcentaje', models.JSONField()),
                ('mto_interes', models.JSONField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fecha_sist', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ano', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=20)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('fecha_sist', models.DateTimeField(auto_now_add=True)),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='arriendos.arriendo')),
            ],
        ),
    ]
