# Generated by Django 5.2.3 on 2025-06-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('Yape', 'Yape'), ('Plin', 'Plin'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
